version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: churn_dw
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/data
      - ./scripts:/scripts
      - ~/.dbt:/root/.dbt

  airflow:
    build: .
    command: bash -c "airflow db init && airflow webserver & airflow scheduler"
    volumes:
      - ./airflow:/app/airflow
      - ./data:/data
      - ./scripts:/app/scripts
      - ~/.dbt:/root/.dbt
      - ./.env:/.env
    environment:
      - AIRFLOW_HOME=/app/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"

volumes:
  pgdata: